---
- name: Install Java 8 on Amazon Linux 2023
  hosts: all
  become: yes
  tasks:
    - name: Update package index
      yum:
        name: '*'
        state: latest

    - name: Install Java 8
      yum:
        name: java-1.8.0-openjdk-devel
        state: present

    - name: Set JAVA_HOME environment variable
      lineinfile:
        path: ~/.bash_profile
        line: 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk'
        create: yes
        state: present
      become: no

    - name: Source bash_profile to apply JAVA_HOME
      shell: source ~/.bash_profile
      become: no
      when: ansible_env.SHELL == '/bin/bash'
...