---
- name: Install Java 8 and Maven 3.8.6 on Amazon Linux 2023
  hosts: all
  become: yes
  tasks:
    - name: Update package index
      yum:
        name: '*'
        state: latest

    - name: Install Amazon Corretto 8 repository
      yum_repository:
        name: amazon-corretto
        description: Amazon Corretto 8
        baseurl: https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.rpm
        gpgcheck: yes
        gpgkey: https://www.amazon.com/amazon-corretto-key.asc
        enabled: yes

    - name: Install Amazon Corretto 8 JDK
      yum:
        name: java-1.8.0-amazon-corretto
        state: present

    - name: Install wget
      yum:
        name: wget
        state: present

    - name: Download Maven 3.8.6
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
        dest: /tmp/apache-maven-3.8.6-bin.tar.gz

    - name: Extract Maven
      unarchive:
        src: /tmp/apache-maven-3.8.6-bin.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Create a symbolic link for Maven
      file:
        src: /opt/apache-maven-3.8.6
        dest: /opt/maven
        state: link

    - name: Set MAVEN_HOME environment variable
      lineinfile:
        path: ~/.bash_profile
        line: 'export MAVEN_HOME=/opt/maven'
        create: yes
        state: present
      become: no

    - name: Set JAVA_HOME environment variable
      lineinfile:
        path: ~/.bash_profile
        line: 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto'
        create: yes
        state: present
      become: no

    - name: Source bash_profile to apply JAVA_HOME and MAVEN_HOME
      shell: source ~/.bash_profile
      become: no
      when: ansible_env.SHELL == '/bin/bash'

    - name: Verify Java version
      command: java -version
      register: java_version
      changed_when: false

    - name: Display Java version
      debug:
        msg: "{{ java_version.stdout }}"

    - name: Verify Maven version
      command: mvn -v
      register: maven_version
      changed_when: false

    - name: Display Maven version
      debug:
        msg: "{{ maven_version.stdout }}"
...