---
- name: Install Java and Maven on Amazon Linux and Red Hat-based systems
  hosts: all
  become: yes
  tasks:
    - name: Install Java and Maven on Amazon Linux or Red Hat-based systems
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'Amazon'
      block:
        - name: Install OpenJDK 11
          yum:
            name: java-11-openjdk
            state: present

        - name: Install Maven
          yum:
            name: maven
            state: present

    - name: Verify Java installation
      command: java -version
      register: java_version
      changed_when: false

    - name: Verify Maven installation
      command: mvn -v
      register: maven_version
      changed_when: false

    - name: Display Java version
      debug:
        msg: "Java version: {{ java_version.stdout_lines }}"

    - name: Display Maven version
      debug:
        msg: "Maven version: {{ maven_version.stdout_lines }}"
...
