---
- name: Install Java 8 on Red Hat and Ubuntu, Java 11 on Debian
  hosts: n5
  become: yes
  tasks:

    - name: Ensure backports repository is present on Debian Stretch
      apt_repository:
        repo: "deb http://deb.debian.org/debian stretch-backports main"
      when: ansible_distribution_release == "stretch"

    - name: Install Java 11 on Debian-based systems
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
      when: ansible_distribution == "Debian"

    - name: Install Java 8 on Ubuntu
      apt:
        name: openjdk-8-jdk
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Java 8 on Red Hat-based systems
      yum:
        name: java-1.8.0-openjdk
        state: present
      when: ansible_distribution in ["RedHat", "CentOS", "Amazon"]

    - name: Set JAVA_HOME and update PATH for Red Hat-based systems
      lineinfile:
        path: /etc/profile.d/java.sh
        line: |
          export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
          export PATH=$JAVA_HOME/bin:$PATH
        create: yes
      when: ansible_distribution in ["RedHat", "CentOS", "Amazon"]

    - name: Set JAVA_HOME and update PATH for Ubuntu with Java 8
      lineinfile:
        path: /etc/profile.d/java.sh
        line: |
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
        create: yes
      when: ansible_distribution == "Ubuntu"

    - name: Set JAVA_HOME and update PATH for Debian with Java 11
      lineinfile:
        path: /etc/profile.d/java.sh
        line: |
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
        create: yes
      when: ansible_distribution == "Debian"

    - name: Verify Java version and Display JAVA_HOME
      shell: |
        java_version=$(java -version 2>&1)
        echo "Java Version: $java_version"
        echo "JAVA_HOME: $JAVA_HOME"
      register: result
      changed_when: false

    - name: Show Java version and JAVA_HOME
      debug:
        msg: |
          Java Setup:
          {{ result.stdout_lines | join('\n') }}
