---
- name: Install Maven compatible with Java 1.8
  hosts: all
  become: yes
  tasks:
    - name: Install Maven from the package manager
      yum:
        name: maven
        state: present

    - name: Check Maven version
      command: mvn -v
      register: mvn_version
      changed_when: false

    - name: Display Maven version
      debug:
        msg: "Maven version installed: {{ mvn_version.stdout }}"
...