- name: Run Maven build
  ansible.builtin.shell:
    cmd: mvn clean package
    chdir: "{{ jenkins_workspace }}/javawebapp"
  environment:
    JAVA_HOME: "{{ java_home }}"
    M2_HOME: "{{ m2_home }}"
    PATH: "{{ java_home }}/bin:{{ m2_home }}/bin:{{ ansible_env.PATH }}"
  register: build_result

- name: Show Maven build result
  ansible.builtin.debug:
    msg: |
      Maven Build Result:
      {{ build_result.stdout }}
      Error Output:
      {{ build_result.stderr }}
