---
- name: perform Maven build and test
  hosts: all
  become: yes
  vars:
    jenkins_workspace: "/home/ec2-user/workspace/JenkinsAnsible"  # Updated path
  tasks:
    - name: Ensure Jenkins workspace directory exists
      ansible.builtin.file:
        path: "{{ jenkins_workspace }}"
        state: directory

    - name: Run Maven build
      ansible.builtin.shell: |
        export JAVA_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto
        export M2_HOME=/opt/apache-maven-3.8.8
        export PATH=$M2_HOME/bin:$PATH
        mvn clean install
      args:
        chdir: "{{ jenkins_workspace }}"

    - name: Run Maven tests
      ansible.builtin.shell: |
        export JAVA_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto
        export M2_HOME=/opt/apache-maven-3.8.8
        export PATH=$M2_HOME/bin:$PATH
        mvn test
      args:
        chdir: "{{ jenkins_workspace }}"
