---
- name: Perform Maven build
  hosts: all
  become: yes
  vars:
    jenkins_workspace: "/path/to/jenkins/workspace"  # Define this path according to your setup
  tasks:
    - name: Run Maven build
      ansible.builtin.shell: |
        export JAVA_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto
        export M2_HOME=/opt/apache-maven-3.8.8
        export PATH=$M2_HOME/bin:$PATH
        mvn clean install
      args:
        chdir: "{{ jenkins_workspace }}"  # Path passed as a variable
