---
- name: perform Maven build and test
  hosts: all
  become: yes
  vars:
    jenkins_workspace: "/home/ec2-user/workspace/JenkinsAnsible"  # Updated path
  tasks:
    - name: Ensure Jenkins workspace directory exists
      ansible.builtin.file:
        path: "{{ jenkins_workspace }}"
        state: directory

    - name: Debug environment variables
      ansible.builtin.shell: |
        echo "JAVA_HOME=$JAVA_HOME"
        echo "M2_HOME=$M2_HOME"
        echo "PATH=$PATH"
      args:
        chdir: "{{ jenkins_workspace }}"
      register: env_vars

    - name: Show environment variables
      ansible.builtin.debug:
        msg: |
          Environment Variables:
          {{ env_vars.stdout }}

    - name: Run Maven build
      ansible.builtin.shell:
        cmd: |
          mvn clean install
        environment:
          JAVA_HOME: "/usr/lib/jvm/java-1.8.0-amazon-corretto"
          M2_HOME: "/opt/apache-maven-3.8.8"
          PATH: "/opt/apache-maven-3.8.8/bin:{{ ansible_env.PATH }}"
      args:
        chdir: "{{ jenkins_workspace }}"

    - name: Run Maven tests
      ansible.builtin.shell:
        cmd: |
          mvn test
        environment:
          JAVA_HOME: "/usr/lib/jvm/java-1.8.0-amazon-corretto"
          M2_HOME: "/opt/apache-maven-3.8.8"
          PATH: "/opt/apache-maven-3.8.8/bin:{{ ansible_env.PATH }}"
      args:
        chdir: "{{ jenkins_workspace }}"
