---
- name: Install Java 8 and Maven 3.3.8
  hosts: all
  become: yes
  tasks:
    - name: Remove existing Java (Amazon Linux 2)
      when: ansible_distribution == 'Amazon'
      package:
        name: java-11-amazon-corretto
        state: absent

    - name: Remove existing Maven (Amazon Linux 2)
      when: ansible_distribution == 'Amazon'
      package:
        name: maven
        state: absent

    - name: Remove existing Java (Red Hat-based systems)
      when: ansible_distribution == 'RedHat'
      yum:
        name: java-11-openjdk
        state: absent

    - name: Remove existing Maven (Red Hat-based systems)
      when: ansible_distribution == 'RedHat'
      yum:
        name: maven
        state: absent

    - name: Remove existing Java (Ubuntu)
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: openjdk-11-jdk
        state: absent

    - name: Remove existing Maven (Ubuntu)
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: maven
        state: absent

    - name: Install Java 8 (Amazon Linux 2)
      when: ansible_distribution == 'Amazon'
      package:
        name: java-1.8.0-amazon-corretto
        state: present

    - name: Install Java 8 (Red Hat-based systems)
      when: ansible_distribution == 'RedHat'
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Install Java 8 (Ubuntu)
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: openjdk-8-jdk
        state: present
...