---
- name: Install Java and Maven on Amazon Linux and Red Hat-based systems
  hosts: all
  become: yes
  tasks:
    - name: Install Java and Maven on Amazon Linux 2 or Red Hat-based systems
      block:
        - name: Install OpenJDK 8 on Amazon Linux 2
          when: ansible_distribution == 'Amazon'
          yum:
            name: java-1.8.0-openjdk
            state: present

        - name: Install Maven on Amazon Linux 2 from a direct URL
          when: ansible_distribution == 'Amazon'
          get_url:
            url: https://archive.apache.org/dist/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
            dest: /tmp/apache-maven-3.8.6-bin.tar.gz

        - name: Extract Maven archive
          when: ansible_distribution == 'Amazon'
          unarchive:
            src: /tmp/apache-maven-3.8.6-bin.tar.gz
            dest: /opt/
            remote_src: yes

        - name: Create symlink for Maven
          when: ansible_distribution == 'Amazon'
          file:
            src: /opt/apache-maven-3.8.6
            dest: /usr/local/maven
            state: link

        - name: Set Maven environment variables
          when: ansible_distribution == 'Amazon'
          lineinfile:
            path: /etc/profile.d/maven.sh
            line: |
              export M2_HOME=/usr/local/maven
              export PATH=${M2_HOME}/bin:${PATH}
            create: yes
            state: present

        - name: Install OpenJDK 11 on Red Hat-based systems
          when: ansible_distribution == 'RedHat'
          yum:
            name: java-11-openjdk
            state: present

        - name: Install Maven on Red Hat-based systems
          when: ansible_distribution == 'RedHat'
          yum:
            name: maven
            state: present

    - name: Verify Java installation
      command: java -version
      register: java_version
      changed_when: false

    - name: Verify Maven installation
      command: mvn -v
      register: maven_version
      changed_when: false

    - name: Display Java version
      debug:
        msg: "Java version: {{ java_version.stdout_lines }}"

    - name: Display Maven version
      debug:
        msg: "Maven version: {{ maven_version.stdout_lines }}"
...