---
- name: Test Java Web Application
  hosts: n1
  become: yes
  vars:
    jenkins_workspace: "/home/ec2-user/workspace/JenkinsAnsible"
    war_file: "{{ jenkins_workspace }}/target/WebAppCal-0.0.7.war"
    java_home: "/usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64/jre"  # Update with the correct path to your Java installation
    m2_home: "/opt/apache-maven-3.8.8"       # Update with the correct path to your Maven installation

  tasks:
    - name: Ensure test workspace directory exists
      ansible.builtin.file:
        path: "{{ jenkins_workspace }}"
        state: directory

    - name: Check if WAR file exists
      ansible.builtin.stat:
        path: "{{ war_file }}"
      register: war_file_stat

    - name: Fail if WAR file does not exist
      ansible.builtin.fail:
        msg: "WAR file not found: {{ war_file }}"
      when: not war_file_stat.stat.exists

    - name: Run Maven tests
      ansible.builtin.shell:
        cmd: mvn test
        chdir: "{{ jenkins_workspace }}"
      environment:
        JAVA_HOME: "{{ java_home }}"
        M2_HOME: "{{ m2_home }}"
        PATH: "{{ java_home }}/bin:{{ m2_home }}/bin:{{ ansible_env.PATH }}"
      register: test_result

    - name: Show Maven test result
      ansible.builtin.debug:
        msg: |
          Maven Test Result:
          {{ test_result.stdout }}
          Error Output:
          {{ test_result.stderr }}
