---
- name: Transfer WAR file path to deployment servers
  hosts: n1
  become: yes
  vars:
    war_file_path_file: "/tmp/war_file_path.txt"
    transfer_file_path: "/tmp/war_file_path.txt"
  
  tasks:
    - name: Ensure /tmp directory exists on build server
      ansible.builtin.file:
        path: "/tmp"
        state: directory

    - name: Check if WAR file path file exists on build server
      ansible.builtin.stat:
        path: "{{ war_file_path_file }}"
      register: war_file_path_stat

    - name: Fail if WAR file path file does not exist
      ansible.builtin.fail:
        msg: "WAR file path file not found: {{ war_file_path_file }}"
      when: not war_file_path_stat.stat.exists

    - name: Fetch WAR file path from build server
      ansible.builtin.fetch:
        src: "{{ war_file_path_file }}"
        dest: "{{ transfer_file_path }}"
        flat: yes

    - name: Ensure /tmp directory exists on deployment servers
      ansible.builtin.file:
        path: "/tmp"
        state: directory
      delegate_to: "{{ item }}"
      with_items:
        - n3
        - n4
        - n5

    - name: Transfer WAR file path to deployment servers
      ansible.builtin.copy:
        src: "{{ transfer_file_path }}"
        dest: "/tmp/war_file_path.txt"
      delegate_to: "{{ item }}"
      with_items:
        - n3
        - n4
        - n5
