---
- name: Deploy Java Web Application
  hosts: deploy
  become: yes
  tasks:
    - name: Create tomcat group if it does not exist
      group:
        name: tomcat
        state: present

    - name: Create tomcat user if it does not exist
      user:
        name: tomcat
        group: tomcat
        system: yes
        shell: /bin/nologin
        state: present

    - name: Ensure Tomcat webapps directory exists
      file:
        path: /opt/tomcat/webapps
        state: directory
        owner: tomcat
        group: tomcat
        mode: '0755'

    - name: Stop Tomcat service
      block:
        - name: Check Tomcat service status
          command: systemctl is-active tomcat
          register: tomcat_status
          failed_when: false
          changed_when: false

        - name: Stop Tomcat service if running
          systemd:
            name: tomcat
            state: stopped
          when: tomcat_status.stdout == "active"

    - name: Deploy WAR file to Tomcat webapps directory
      copy:
        src: "/tmp/WebAppCal-0.0.7.war"
        dest: /opt/tomcat/webapps/WebAppCal.war
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Start Tomcat service
      block:
        - name: Ensure Tomcat service is enabled and started
          systemd:
            name: tomcat
            enabled: yes
            state: started

        - name: Check Tomcat service status
          command: systemctl status tomcat
          register: tomcat_service_status

    - name: Show Tomcat service status
      debug:
        msg: "{{ tomcat_service_status.stdout }}"

    - name: Verify Tomcat service is running
      command: systemctl is-active tomcat
      register: tomcat_running
      failed_when: tomcat_running.stdout != "active"
      changed_when: false
