- name: Deploy Java Web Application
  hosts: deploy
  become: yes
  vars:
    tomcat_webapps_dir: "/opt/tomcat/webapps"
    war_file_path_file: "/tmp/war_file_path.txt"
    app_name: "WebAppCal"

  tasks:
    - name: Verify that the WAR file path exists
      ansible.builtin.stat:
        path: "{{ war_file_path_file }}"
      register: war_file_stat

    - name: Fail if WAR file path file does not exist
      ansible.builtin.fail:
        msg: "WAR file path file not found: {{ war_file_path_file }}"
      when: not war_file_stat.stat.exists

    - name: Read WAR file path from file
      ansible.builtin.slurp:
        src: "{{ war_file_path_file }}"
      register: war_file_path_slurp
      when: war_file_stat.stat.exists

    - name: Set WAR file path as variable
      ansible.builtin.set_fact:
        war_file: "{{ war_file_path_slurp.content | b64decode | trim }}"
      when: war_file_stat.stat.exists

    # The rest of your deployment tasks
