---
- name: Deploy Java Web Application
  hosts: deploy
  become: yes
  vars:
    tomcat_service_name: "{{ 'tomcat' if ansible_distribution == 'Ubuntu' else 'tomcat' if ansible_distribution == 'Debian' else 'tomcat' }}"
    tomcat_webapps_dir: "/var/lib/tomcat/webapps"  # Update this if necessary

  tasks:
    - name: Read WAR file path from file
      ansible.builtin.slurp:
        src: /tmp/war_file_path.txt
      register: war_file_path

    - name: Decode WAR file path
      ansible.builtin.set_fact:
        war_file_path: "{{ war_file_path['content'] | b64decode }}"

    - name: Ensure Tomcat webapps directory exists
      ansible.builtin.file:
        path: "{{ tomcat_webapps_dir }}"
        state: directory

    - name: Stop Tomcat service (Debian/Ubuntu-based)
      ansible.builtin.systemd:
        name: "{{ tomcat_service_name }}"
        state: stopped
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Stop Tomcat service (Red Hat-based)
      ansible.builtin.systemd:
        name: "{{ tomcat_service_name }}"
        state: stopped
      when: ansible_distribution in ['RedHat', 'CentOS']

    - name: Copy WAR file to Tomcat webapps directory
      ansible.builtin.copy:
        src: "{{ war_file_path }}"
        dest: "{{ tomcat_webapps_dir }}/WebAppCal.war"
    
    - name: Start Tomcat service (Debian/Ubuntu-based)
      ansible.builtin.systemd:
        name: "{{ tomcat_service_name }}"
        state: started
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Start Tomcat service (Red Hat-based)
      ansible.builtin.systemd:
        name: "{{ tomcat_service_name }}"
        state: started
      when: ansible_distribution in ['RedHat', 'CentOS']
