---
- name: Install Java 8
  hosts: deploy
  become: yes
  tasks:
    - name: Install Java 8
      yum:
        name: java-1.8.0-amazon-corretto
        state: present

    - name: Set JAVA_HOME and update PATH
      lineinfile:
        path: /etc/profile.d/java.sh
        line: |
          export JAVA_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto
          export PATH=$JAVA_HOME/bin:$PATH
        create: yes

    - name: Verify Java version and Display JAVA_HOME
      shell: |
        java_version=$(java -version 2>&1)
        echo "Java Version: $java_version"
        echo "JAVA_HOME: $JAVA_HOME"
      register: result
      changed_when: false

    - name: Show Java version and JAVA_HOME
      debug:
        msg: |
          Java Setup:
          {{ result.stdout_lines | join('\n') }}
...
