---
- name: Install Java 8 and Maven 3.3.8
  hosts: all
  become: yes
  tasks:
    - name: Install Java 8 (Amazon Linux 2)
      when: ansible_distribution == 'Amazon'
      package:
        name: java-1.8.0-amazon-corretto
        state: present

    - name: Install Java 8 (Red Hat-based systems)
      when: ansible_distribution == 'RedHat'
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Install Java 8 (Ubuntu)
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: openjdk-8-jdk
        state: present
...