---
- name: Install Java and Maven on Amazon Linux 2
  hosts: n1
  become: yes
  tasks:
    - name: Update package repository
      package:
        name: "*"
        state: latest

    - name: Install Java 11
      package:
        name: java-11-amazon-corretto
        state: present

    - name: Install Maven
      package:
        name: maven
        state: present
...