- name: Verify Java and Maven installation
  hosts: n1
  become: yes
  tasks:
    - name: Check Java installation path
      command: ls -l /usr/local/java/bin/java
      register: java_path_check
      ignore_errors: yes

    - name: Check Maven installation path
      command: ls -l /usr/local/maven/bin/mvn
      register: maven_path_check
      ignore_errors: yes

    - name: Display Java installation path check
      debug:
        msg: "Java installation path: {{ java_path_check.stdout_lines | default('Java not found') }}"

    - name: Display Maven installation path check
      debug:
        msg: "Maven installation path: {{ maven_path_check.stdout_lines | default('Maven not found') }}"

    - name: Verify Java installation
      command: /usr/local/java/bin/java -version
      register: java_version
      ignore_errors: yes

    - name: Verify Maven installation
      command: /usr/local/maven/bin/mvn -v
      register: maven_version
      ignore_errors: yes

    - name: Display Java version or error
      debug:
        msg: "{{ java_version.stdout_lines | default('Java installation failed.') }}"

    - name: Display Maven version or error
      debug:
        msg: "{{ maven_version.stdout_lines | default('Maven installation failed.') }}"
