---
- name: Install Java and Maven on Amazon Linux 2
  hosts: n1
  become: yes
  tasks:
    - name: Update package repository
      package:
        name: "*"
        state: latest

    - name: Install Java 11
      package:
        name: java-11-amazon-corretto
        state: present

    - name: Install Maven
      package:
        name: maven
        state: present

    - name: Check Java version
      command: java -version
      register: java_version_output
      ignore_errors: yes

    - name: Display Java version
      debug:
        msg: "{{ java_version_output.stderr_lines }}"

    - name: Check Maven version
      command: mvn -v
      register: maven_version_output
      ignore_errors: yes

    - name: Display Maven version
      debug:
        msg: "{{ maven_version_output.stdout_lines }}"
...