---
- name: Install Java and Maven on Amazon Linux 2
  hosts: amazon_linux
  become: yes
  tasks:
    - name: Update package repository
      amazon.aws.aws_ssm:
        name: amazon-linux-extras
        state: present

    - name: Install Java 11
      package:
        name: java-11-amazon-corretto
        state: present

    - name: Install Maven
      package:
        name: maven
        state: present
...