- name: Verify Java and Maven installation
  hosts: n1
  become: yes
  tasks:
    - name: Ensure Java installation path exists
      file:
        path: /usr/local/java/bin/java
        state: file
      register: java_path_check

    - name: Ensure Maven installation path exists
      file:
        path: /usr/local/maven/bin/mvn
        state: file
      register: maven_path_check

    - name: Display Java installation path check
      debug:
        msg: "Java installation path: {{ java_path_check.path | default('Java not found') }}"

    - name: Display Maven installation path check
      debug:
        msg: "Maven installation path: {{ maven_path_check.path | default('Maven not found') }}"

    - name: Verify Java installation
      command: /usr/local/java/bin/java -version
      register: java_version
      ignore_errors: yes

    - name: Verify Maven installation
      command: /usr/local/maven/bin/mvn -v
      register: maven_version
      ignore_errors: yes

    - name: Display Java version or error
      debug:
        msg: "{{ java_version.stdout_lines | default('Java installation failed.') }}"

    - name: Display Maven version or error
      debug:
        msg: "{{ maven_version.stdout_lines | default('Maven installation failed.') }}"
