---
- name: Install Java and Maven on Amazon Linux
  hosts: n1
  become: yes
  tasks:
    - name: Download OpenJDK 17 tarball
      get_url:
        url: https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
        dest: /tmp/jdk-17_linux-x64_bin.tar.gz

    - name: Extract OpenJDK 17
      unarchive:
        src: /tmp/jdk-17_linux-x64_bin.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Create symlink for Java
      file:
        src: /opt/jdk-17
        dest: /usr/local/java
        state: link
        force: yes

    - name: Download Maven tarball
      get_url:
        url: https://archive.apache.org/dist/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
        dest: /tmp/apache-maven-3.8.6-bin.tar.gz

    - name: Extract Maven archive
      unarchive:
        src: /tmp/apache-maven-3.8.6-bin.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Create symlink for Maven
      file:
        src: /opt/apache-maven-3.8.6
        dest: /usr/local/maven
        state: link
        force: yes

    - name: Create java.sh to set JAVA_HOME
      copy:
        dest: /etc/profile.d/java.sh
        content: |
          export JAVA_HOME=/usr/local/java
          export PATH=$JAVA_HOME/bin:$PATH
        mode: '0644'

    - name: Create maven.sh to set M2_HOME
      copy:
        dest: /etc/profile.d/maven.sh
        content: |
          export M2_HOME=/usr/local/maven
          export PATH=$M2_HOME/bin:$PATH
        mode: '0644'

    - name: Apply environment variables
      shell: source /etc/profile.d/java.sh && source /etc/profile.d/maven.sh

    - name: Verify Java installation
      command: /usr/local/java/bin/java -version
      register: java_version
      ignore_errors: yes

    - name: Verify Maven installation
      command: /usr/local/maven/bin/mvn -v
      register: maven_version
      ignore_errors: yes

    - name: Display Java version or error
      debug:
        msg: "{{ java_version.stdout_lines | default('Java installation failed.') }}"

    - name: Display Maven version or error
      debug:
        msg: "{{ maven_version.stdout_lines | default('Maven installation failed.') }}"
...
