---
- name: Perform Maven test
  hosts: n1
  become: yes
  vars:
    jenkins_workspace: "/home/ec2-user/workspace/JenkinsAnsible"
    java_home: "/usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64/jre"
    m2_home: "/opt/apache-maven-3.8.8"
  tasks:
    - name: Run Maven tests
      ansible.builtin.shell:
        cmd: mvn test
        chdir: "{{ jenkins_workspace }}"
      environment:
        JAVA_HOME: "{{ java_home }}"
        M2_HOME: "{{ m2_home }}"
        PATH: "{{ java_home }}/bin:{{ m2_home }}/bin:{{ ansible_env.PATH }}"
      register: test_result

    - name: Show Maven test result
      ansible.builtin.debug:
        msg: |
          Maven Test Result:
          {{ test_result.stdout }}
          Error Output:
          {{ test_result.stderr }}
