---
- name: Install Java 8 on Amazon Linux 2023
  hosts: n1
  become: yes
  tasks:
    - name: Update package index
      yum:
        name: '*'
        state: latest

    - name: Install wget (for downloading files if needed)
      yum:
        name: wget
        state: present

    - name: Install Amazon Corretto 8 repository
      yum_repository:
        name: amazon-corretto
        description: Amazon Corretto 8
        baseurl: https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.rpm
        gpgcheck: yes
        gpgkey: https://www.amazon.com/amazon-corretto-key.asc
        enabled: yes

    - name: Install Amazon Corretto 8 JDK
      yum:
        name: java-1.8.0-amazon-corretto
        state: present

    - name: Set JAVA_HOME environment variable
      lineinfile:
        path: ~/.bash_profile
        line: 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto'
        create: yes
        state: present
      become: no

    - name: Set PATH to include JAVA_HOME
      lineinfile:
        path: ~/.bash_profile
        line: 'export PATH=$JAVA_HOME/bin:$PATH'
        create: yes
        state: present
      become: no

    - name: Source bash_profile to apply JAVA_HOME and PATH
      shell: source ~/.bash_profile
      become: no
      when: ansible_env.SHELL == '/bin/bash'

    - name: Verify Java version
      command: java -version
      register: java_version
      changed_when: false

    - name: Display Java version
      debug:
        msg: "{{ java_version.stdout }}"
...