---
- name: Verify Java and Maven Paths
  hosts: all
  become: yes
  tasks:
    - name: Find Java installation path
      command: "which java"
      register: java_path
      changed_when: false

    - name: Find Java home directory from java path
      shell: |
        if [ -x "$(command -v java)" ]; then
          readlink -f $(which java) | sed "s:/bin/java::"
        else
          echo "Java not found"
        fi
      register: java_home
      changed_when: false

    - name: Find Maven installation path
      command: "which mvn"
      register: maven_path
      changed_when: false

    - name: Find Maven home directory from mvn path
      shell: |
        if [ -x "$(command -v mvn)" ]; then
          readlink -f $(which mvn) | sed "s:/bin/mvn::"
        else
          echo "Maven not found"
        fi
      register: maven_home
      changed_when: false

    - name: Verify Java executable
      stat:
        path: "{{ java_path.stdout }}"
      register: java_stat

    - name: Verify Java home directory
      stat:
        path: "{{ java_home.stdout }}"
      register: java_home_stat

    - name: Verify Maven executable
      stat:
        path: "{{ maven_path.stdout }}"
      register: maven_stat

    - name: Verify Maven home directory
      stat:
        path: "{{ maven_home.stdout }}"
      register: maven_home_stat

    - name: Show Java and Maven paths
      debug:
        msg: |
          Java Path: {{ java_path.stdout }}
          Java Home Directory: {{ java_home.stdout }}
          Maven Path: {{ maven_path.stdout }}
          Maven Home Directory: {{ maven_home.stdout }}

    - name: Check Java executable status
      debug:
        msg: "Java executable is present: {{ java_stat.stat.exists }}"

    - name: Check Java home directory status
      debug:
        msg: "Java home directory is present: {{ java_home_stat.stat.exists }}"

    - name: Check Maven executable status
      debug:
        msg: "Maven executable is present: {{ maven_stat.stat.exists }}"

    - name: Check Maven home directory status
      debug:
        msg: "Maven home directory is present: {{ maven_home_stat.stat.exists }}"
