---
- name: Install Java 8 and verify version on Amazon Linux 2023
  hosts: n1
  become: yes
  tasks:
    - name: Install Java 8 and wget
      yum:
        name:
          - java-1.8.0-amazon-corretto
          - wget
        state: present

    - name: Set JAVA_HOME and PATH
      shell: |
        echo 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto' >> ~/.bash_profile
        echo 'export PATH=$JAVA_HOME/bin:$PATH' >> ~/.bash_profile
        source ~/.bash_profile

    - name: Verify Java version and Display JAVA_HOME
      shell: |
        java_version=$(java -version 2>&1)
        echo "Java Version: $java_version"
        echo "JAVA_HOME: $JAVA_HOME"
      register: result
      changed_when: false

    - name: Show Java version and JAVA_HOME
      debug:
        msg: |
          {{ result.stdout_lines | join('\n') }}
...