---
- name: Install Java 8 and verify version on Amazon Linux 2023
  hosts: n1
  become: yes
  tasks:
    - name: Install Java 8 and wget
      yum:
        name:
          - java-1.8.0-amazon-corretto
          - wget
        state: present

    - name: Set JAVA_HOME and PATH
      shell: |
        echo 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto' >> ~/.bash_profile
        echo 'export PATH=$JAVA_HOME/bin:$PATH' >> ~/.bash_profile
        source ~/.bash_profile

    - name: Verify Java version
      command: java -version
      register: java_version
      changed_when: false

    - name: Show Java version
      debug:
        msg: "{{ java_version.stderr_lines | join('') }}"

    - name: Display JAVA_HOME path
      shell: echo $JAVA_HOME
      register: java_home_path
      changed_when: false

    - name: Show JAVA_HOME path
      debug:
        msg: "JAVA_HOME is set to: {{ java_home_path.stdout }}"
...