---
- name: Install Jenkins on CentOS
  hosts: centos
  become: yes
  tasks:
    - name: Backup existing CentOS repository configuration
      command: mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup
      ignore_errors: yes

    - name: Create new CentOS Vault repository configuration
      copy:
        dest: /etc/yum.repos.d/CentOS-Vault.repo
        content: |
          [base]
          name=CentOS-$releasever - Base
          baseurl=http://vault.centos.org/7.9.2009/os/x86_64/
          gpgcheck=1
          gpgkey=http://vault.centos.org/7.9.2009/updates/x86_64/Packages/centos-gpg-keys-7-0.el7.noarch.rpm
          enabled=1

          [updates]
          name=CentOS-$releasever - Updates
          baseurl=http://vault.centos.org/7.9.2009/updates/x86_64/
          gpgcheck=1
          gpgkey=http://vault.centos.org/7.9.2009/updates/x86_64/Packages/centos-gpg-keys-7-0.el7.noarch.rpm
          enabled=1

    - name: Clean yum cache
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Install Java OpenJDK 11
      yum:
        name: java-11-openjdk
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Configure firewall to allow Jenkins port
      firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: yes
        port: 8080/tcp
...