---
- name: Install Jenkins on CentOS
  hosts: n4
  become: yes
  tasks:
    - name: Ensure EPEL repository is enabled
      yum:
        name: epel-release
        state: present

    - name: Install Java (required by Jenkins)
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/redhat/jenkins.io.key
        dest: /etc/pki/rpm-gpg/jenkins.io.key

    - name: Import Jenkins GPG key
      rpm_key:
        key: /etc/pki/rpm-gpg/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins-stable repo
        baseurl: https://pkg.jenkins.io/redhat-stable/
        gpgkey: file:///etc/pki/rpm-gpg/jenkins.io.key
        gpgcheck: 1
        enabled: yes

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Open firewall port 8080 for Jenkins
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Reload firewall to apply changes
      firewalld:
        state: reloaded
...