---
- name: Install Jenkins on CentOS
  hosts: n4
  become: yes
  tasks:
    - name: Ensure EPEL repository is enabled
      yum:
        name: epel-release
        state: present

    - name: Install Java (required by Jenkins)
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/redhat/jenkins.io.key
        dest: /etc/pki/rpm-gpg/jenkins.io.key

    - name: Import Jenkins GPG key
      rpm_key:
        key: /etc/pki/rpm-gpg/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins-stable repo
        baseurl: https://pkg.jenkins.io/redhat-stable/
        gpgkey: file:///etc/pki/rpm-gpg/jenkins.io.key
        gpgcheck: 1
        enabled: yes

    - name: Ensure base repository is configured correctly
      block:
        - name: Backup existing CentOS Base repo configuration
          command: cp /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.bak
          when: ansible_os_family == 'RedHat'

        - name: Configure CentOS Base repo
          copy:
            content: |
              [base]
              name=CentOS-$releasever - Base
              baseurl=http://mirror.centos.org/centos/$releasever/os/$basearch/
              gpgcheck=1
              gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
              
              [updates]
              name=CentOS-$releasever - Updates
              baseurl=http://mirror.centos.org/centos/$releasever/updates/$basearch/
              gpgcheck=1
              gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
            dest: /etc/yum.repos.d/CentOS-Base.repo
          when: ansible_os_family == 'RedHat'

    - name: Clean yum cache
      command: yum clean all

    - name: Update yum repository metadata
      command: yum makecache

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Open firewall port 8080 for Jenkins
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Reload firewall to apply changes
      firewalld:
        state: reloaded
...