---
- name: Install Jenkins on CentOS
  hosts: centos
  become: yes
  tasks:
    - name: Ensure EPEL repository is enabled
      yum:
        name: epel-release
        state: present

    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Import Jenkins GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat/jenkins.io.key
        state: present

    - name: Add Jenkins repository configuration
      yum_repository:
        name: jenkins
        description: Jenkins-stable repo
        baseurl: https://pkg.jenkins.io/redhat-stable/
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
        enabled: yes

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Ensure Jenkins is listening on port 8080
      wait_for:
        port: 8080
        delay: 10
...