---
- name: Find Java and Maven Paths
  hosts: all
  become: yes
  tasks:
    - name: Find Java executable path
      command: which java
      register: java_path
      ignore_errors: yes

    - name: Find Maven executable path
      command: which mvn
      register: maven_path
      ignore_errors: yes

    - name: Display Java path
      debug:
        msg: "Java executable path: {{ java_path.stdout | default('Java not found.') }}"

    - name: Display Maven path
      debug:
        msg: "Maven executable path: {{ maven_path.stdout | default('Maven not found.') }}"
...