---
- name: Show Java Installation Path
  hosts: all
  become: yes
  tasks:
    - name: Check if Java is installed
      command: which java
      register: java_location
      ignore_errors: yes

    - name: Find Java installation path
      shell: |
        if [ -x "$(which java)" ]; then
          readlink -f $(which java) | sed "s:bin/java::"
        else
          echo "Java is not installed."
        fi
      register: java_path
      when: java_location.stdout != ""

    - name: Set default message if Java is not installed
      set_fact:
        java_path: "Java is not installed."
      when: java_location.stdout == ""

    - name: Display Java installation path
      debug:
        msg: "Java installation path: {{ java_path.stdout }}"
...