---
- name: Find Maven path
  hosts: g2
  tasks:
    - name: Find Maven executable
      command: which mvn
      register: mvn_path
      ignore_errors: yes

    - name: Display Maven path
      debug:
        msg: "Maven is located at: {{ mvn_path.stdout }}"
      when: mvn_path.stdout is defined and mvn_path.stdout != ""
...