---
- name: Ensure Java is installed and JAVA_HOME is set
  hosts: g2
  become: yes
  tasks:
    - name: Install OpenJDK
      package:
        name: java-1.8.0-openjdk
        state: present

    - name: Find Java installation path
      command: readlink -f $(which java)
      register: java_path

    - name: Create JAVA_HOME environment file
      copy:
        dest: /etc/profile.d/java.sh
        content: |
          # Set JAVA_HOME
          export JAVA_HOME={{ java_path.stdout | dirname | dirname }}
        mode: '0644'
        owner: root
        group: root

    - name: Ensure JAVA_HOME is set for the current session
      shell: |
        source /etc/profile.d/java.sh
        echo $JAVA_HOME
      register: java_home_check

    - name: Print JAVA_HOME value
      debug:
        msg: "JAVA_HOME is set to {{ java_home_check.stdout }}"
...