---
- name: Install Java 8 on Amazon Linux 2
  hosts: n1
  become: yes
  tasks:

    - name: Install Amazon Corretto 8 (Java 8)
      yum:
        name: java-1.8.0-amazon-corretto
        state: present

    - name: Find Java 8 installation path
      command: find /usr/lib/jvm -type d -name "java-1.8.0-amazon-corretto*"
      register: java_paths
      changed_when: false

    - name: Set Java 8 as the default version
      alternatives:
        name: java
        link: /usr/bin/java
        path: "{{ item }}/bin/java"
        priority: 1
      loop: "{{ java_paths.stdout_lines }}"
      when: item is search('/usr/lib/jvm/java-1.8.0-amazon-corretto')

    - name: Verify Java installation
      command: java -version
      register: java_version_output
      ignore_errors: yes

    - name: Display Java version
      debug:
        var: java_version_output.stdout
...