---
- name: Install Java 11 on Amazon Linux 2
  hosts: n1
  become: yes
  tasks:

    - name: Install Amazon Corretto 11 (Java 11)
      yum:
        name: java-11-amazon-corretto
        state: present

    - name: Set Java 11 as the default version
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/java-11-amazon-corretto/bin/java
        priority: 1

    - name: Verify Java installation
      command: java -version
      register: java_version_output
      ignore_errors: yes

    - name: Display Java version
      debug:
        var: java_version_output.stdout
...