---
- name: Install Java 11 on Amazon Linux 2
  hosts: n1
  become: yes
  tasks:

    - name: Install Amazon Corretto 11 (Java 11)
      yum:
        name: java-11-amazon-corretto
        state: present

    - name: Find Java 11 installation path
      command: find /usr/lib/jvm -name "java" -type f -exec dirname {} \; | grep "java-11-amazon-corretto"
      register: java_paths
      changed_when: false

    - name: Set Java 11 as the default version
      alternatives:
        name: java
        link: /usr/bin/java
        path: "{{ item }}/bin/java"
        priority: 1
      loop: "{{ java_paths.stdout_lines }}"
      when: item is search('/usr/lib/jvm/java-11-amazon-corretto')

    - name: Verify Java installation
      command: java -version
      register: java_version_output
      ignore_errors: yes

    - name: Display Java version
      debug:
        var: java_version_output.stdout
...