---
- name: Install Java 11 on Amazon Linux 2
  hosts: n1
  become: yes
  tasks:

    - name: Install Amazon Corretto 11 (Java 11)
      yum:
        name: java-11-amazon-corretto
        state: present

    - name: Discover the correct Java 11 path
      command: alternatives --display java | grep 'priority' | awk '{print $1}'
      register: java_alternatives

    - name: Set Java 11 as the default version
      alternatives:
        name: java
        link: /usr/bin/java
        path: "{{ item }}"
        priority: 1
      loop: "{{ java_alternatives.stdout_lines }}"
      when: item == "/usr/lib/jvm/java-11-amazon-corretto.x86_64/bin/java"

    - name: Verify Java installation
      command: java -version
      register: java_version_output
      ignore_errors: yes

    - name: Display Java version
      debug:
        var: java_version_output.stdout
...