---
- name: Install Zulu OpenJDK 8 on Debian-based Systems
  hosts: all
  become: yes

  tasks:
    # Step 1: Install the Zulu Repository
    - name: Install required packages
      apt:
        name:
          - wget
          - gnupg2
        state: present
        update_cache: yes

    - name: Import Zulu repository GPG key
      apt_key:
        url: https://repos.azul.com/azul-repo.key
        state: present

    - name: Add the Zulu repository
      apt_repository:
        repo: "deb https://repos.azul.com/zulu/deb stable main"
        state: present

    - name: Update the package list after adding Zulu repository
      apt:
        update_cache: yes

    # Step 2: Install Java 8
    - name: Install Zulu OpenJDK 8
      apt:
        name: zulu-8
        state: present

    - name: Verify Java installation
      command: java -version
      register: java_version
      ignore_errors: yes

    - name: Display Java version
      debug:
        msg: "{{ java_version.stderr_lines }}"
      when: java_version.rc == 0

    - name: Fail if Java installation failed
      fail:
        msg: "Java installation failed. Please check the logs."
      when: java_version.rc != 0
