---
- name: Install Zulu OpenJDK Repository and Java 8
  hosts: all
  become: yes

  tasks:
    - name: Remove AdoptOpenJDK repository
      apt_repository:
        repo: "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ bookworm main"
        state: absent
      ignore_errors: yes

    - name: Remove AdoptOpenJDK list file if it exists
      file:
        path: /etc/apt/sources.list.d/adoptopenjdk.list
        state: absent
      ignore_errors: yes

    - name: Install required packages
      apt:
        name: 
          - wget
          - gnupg2
        state: present
        update_cache: yes

    - name: Download Zulu repository key
      get_url:
        url: https://repos.azul.com/azul-repo.key
        dest: /tmp/zulu-repo.key

    - name: Convert Zulu repository key to gpg format
      command: gpg --dearmor -o /usr/share/keyrings/zulu-archive-keyring.gpg /tmp/zulu-repo.key
      args:
        creates: /usr/share/keyrings/zulu-archive-keyring.gpg

    - name: Add the Zulu repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/zulu-archive-keyring.gpg] https://repos.azul.com/zulu/deb stable main"
        state: present

    - name: Update the package list
      apt:
        update_cache: yes

    - name: Install Zulu OpenJDK 8
      apt:
        name: zulu-8
        state: present

    - name: Verify Java installation
      command: java -version
      register: java_version_output
      ignore_errors: yes

    - name: Display Java version
      debug:
        msg: "{{ java_version_output.stdout }}"
