---
- name: Install Zulu OpenJDK Repository and Java 8
  hosts: all
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name: 
          - wget
          - gnupg2
        state: present
        update_cache: yes

    - name: Import Zulu repository key
      apt_key:
        url: https://repos.azul.com/azul-repo.key
        state: present

    - name: Add the Zulu repository
      apt_repository:
        repo: "deb https://repos.azul.com/zulu/deb stable main"
        state: present

    - name: Update the package list
      apt:
        update_cache: yes

    - name: Install Zulu OpenJDK 8
      apt:
        name: zulu-8
        state: present

    - name: Verify Java installation
      command: java -version
      register: java_version_output
      ignore_errors: yes

    - name: Display Java version
      debug:
        msg: "{{ java_version_output.stdout }}"
