---
- name: Install Java 8 Manually on Debian
  hosts: n5
  become: yes
  tasks:

    - name: Download Java 8 from Oracle
      get_url:
        url: https://path_to_java8_download.tar.gz
        dest: /tmp/java8.tar.gz

    - name: Extract Java 8
      unarchive:
        src: /tmp/java8.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Set JAVA_HOME and update PATH
      lineinfile:
        path: /etc/profile.d/java.sh
        line: |
          export JAVA_HOME=/opt/jdk1.8.0_XXX
          export PATH=$JAVA_HOME/bin:$PATH
        create: yes

    - name: Verify Java version and Display JAVA_HOME
      shell: |
        java_version=$(java -version 2>&1)
        echo "Java Version: $java_version"
        echo "JAVA_HOME: $JAVA_HOME"
      register: result
      changed_when: false

    - name: Show Java version and JAVA_HOME
      debug:
        msg: |
          Java Setup:
          {{ result.stdout_lines | join('\n') }}
