- name: Fix Tomcat permissions
  hosts: deploy
  become: yes
  tasks:
    - name: Ensure Tomcat user and group exist
      ansible.builtin.group:
        name: tomcat
        state: present

    - name: Create Tomcat user
      ansible.builtin.user:
        name: tomcat
        group: tomcat
        shell: /sbin/nologin
        create_home: no

    - name: Set ownership for Tomcat directory
      ansible.builtin.file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Set permissions for Tomcat files
      ansible.builtin.file:
        path: /opt/tomcat/bin/startup.sh
        mode: 'u+x'
        owner: tomcat
        group: tomcat

    - name: Ensure Tomcat logs and temp directories are writable
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 'u+rwx'
        owner: tomcat
        group: tomcat
      with_items:
        - /opt/tomcat/logs
        - /opt/tomcat/temp

    - name: Restart Tomcat service
      ansible.builtin.systemd:
        name: tomcat
        state: restarted
